### PR TITLE
Feature/add more raw data parsing digita

### PR DESCRIPTION
**Pull request by puthans**
moved thing park sensors related extraction of  DevEuiUplink object to fvhiot from mittaridatapumppu-parser app.
this makes mdp-parser generic to be used for other data pipeline.

review in conjunction with https://github.com/City-of-Helsinki/mittaridatapumppu-parser/pull/12

### CODE REVIEW

**Review by aapris — CHANGES_REQUESTED** [review]
Let's not put any Thingpark related stuff in fvhiot.parsers because there are other LoRaWAN networks and payload envelope formats. A better place could be e.g. fvhiot.utils.thingpark. Or perhaps even fvhiot.utils.lorawan.thingpark.

**Review by aapris — CHANGES_REQUESTED** [review]
Sorry, I cannot approve this. Having exactly the same 
`create_datalines_from_raw_unpacked_data(unpacked_data: dict)`
duplicated function in all parser modules is against DRY principle.

We have to figure out some other solution to do this.

**Comment by puthans** [comment]
@aapris 
the function actually calls a different parser function in the end, So the code could be changed to for eg: 

def create_datalines_from_raw_unpacked_data(unpacked_data: dict) -> list:
    """
    parse raw data from unpacked_data
    Return well-known parsed data formatted list of data and packet timestamp
    """
    uplink_obj = get_uplink_obj(unpacked_data)
    packet_timestamp = get_packet_timestamp(uplink_obj)
    values = parse_sensornode(uplink_obj.payload_hex, uplink_obj.FPort)
    datalines = [{"time": uplink_obj.Time, "data": values}]
    return packet_timestamp, datalines

In the earlier version of the parsers, all parsers has function create_datalines too which took a parsed version of data as arguments. my idea was to have a similar function but takes raw data as arguments.

**Comment by aapris** [comment]
Ok, I'll merge this now, because it seems it won't break anything and we need to move on. We can check later how to get rid of duplicated functions/code.

**Pull request merged**
